const carian = (input) => {
    input = input.replace(/a/g, "𐊠");
    input = input.replace(/e2/g, "𐋏");
    input = input.replace(/r2/g, "𐋉");
    input = input.replace(/z2/g, "𐋂");
    input = input.replace(/b/g, "𐊡");
    input = input.replace(/d/g, "𐊢");
    input = input.replace(/l/g, "𐊣");
    input = input.replace(/y3/g, "𐋈");
    input = input.replace(/y2/g, "𐋐");
    input = input.replace(/ý/g, "𐊻");
    input = input.replace(/'y/g, "𐊻");
    input = input.replace(/y/g, "𐊤");
    input = input.replace(/r/g, "𐊥");
    input = input.replace(/L2/g, "𐋎");
    input = input.replace(/L/g, "𐊦");
    input = input.replace(/A2/g, "𐊧");
    input = input.replace(/q/g, "𐊨");
    input = input.replace(/b/g, "𐊩");
    input = input.replace(/m/g, "𐊪");
    input = input.replace(/o/g, "𐊫");
    input = input.replace(/D2/g, "𐊬");
    input = input.replace(/t/g, "𐊭");
    input = input.replace(/sh2/g, "𐊯");
    input = input.replace(/sh/g, "𐊮");
    input = input.replace(/'s/g, "𐊸");
    input = input.replace(/ś/g, "𐊸");
    input = input.replace(/s/g, "𐊰");
    input = input.replace(/18/g, "𐊱");
    input = input.replace(/u/g, "𐊲");
    input = input.replace(/N/g, "𐊳");
    input = input.replace(/c/g, "𐊴");
    input = input.replace(/n/g, "𐊵");
    input = input.replace(/T2/g, "𐊶");
    input = input.replace(/p/g, "𐊷");
    input = input.replace(/i/g, "𐊹");
    input = input.replace(/e/g, "𐊺");
    input = input.replace(/k2/g, "𐊽");
    input = input.replace(/k/g, "𐊼");
    input = input.replace(/dh/g, "𐊾");
    input = input.replace(/w/g, "𐊿");
    input = input.replace(/G2/g, "𐋁");
    input = input.replace(/G/g, "𐋀");
    input = input.replace(/z/g, "𐋃");
    input = input.replace(/ng/g, "𐋄");
    input = input.replace(/j/g, "𐋅");
    input = input.replace(/39/g, "𐋆");
    input = input.replace(/T/g, "𐋇");
    input = input.replace(/mb2/g, "𐋋");
    input = input.replace(/mb3/g, "𐋌");
    input = input.replace(/mb4/g, "𐋍");
    input = input.replace(/mb/g, "𐋊");
;
    return input;
}

export default carian;
