const oldslavic = (input) => {
    // input = input.replace(/A/g, "А");
    // input = input.replace(/a/g, "а");
    // input = input.replace(/B/g, "Б");
    // input = input.replace(/b/g, "б");
    // input = input.replace(/V/g, "В");
    // input = input.replace(/v/g, "в");
    // input = input.replace(/G'/g, "Ћ");
    // input = input.replace(/g'/g, "ћ");
    // input = input.replace(/G/g, "Г");
    // input = input.replace(/g/g, "г");
    // input = input.replace(/E/g, "Е");
    // input = input.replace(/e/g, "є");
    // input = input.replace(/Ž/g, "Ж");
    // input = input.replace(/ž/g, "ж");
    // input = input.replace(/Dz/g, "Ѕ");
    // input = input.replace(/dz/g, "ѕ");
    // input = input.replace(/D/g, "Д");
    // input = input.replace(/d/g, "д");
    // input = input.replace(/Z/g, "З");
    // input = input.replace(/z/g, "з");
    // input = input.replace(/I/g, "Ꙇ");
    // input = input.replace(/i/g, "ꙇ");
    // input = input.replace(/I/g, "И");
    // input = input.replace(/i/g, "и");
    // input = input.replace(/K/g, "К");
    // input = input.replace(/k/g, "к");
    // input = input.replace(/L/g, "Л");
    // input = input.replace(/l/g, "л");
    // input = input.replace(/M/g, "М");
    // input = input.replace(/m/g, "м");
    // input = input.replace(/N/g, "Н");
    // input = input.replace(/n/g, "н");
    // input = input.replace(/O/g, "О");
    // input = input.replace(/o/g, "о");
    // input = input.replace(/P/g, "П");
    // input = input.replace(/p/g, "п");
    // input = input.replace(/R/g, "Р");
    // input = input.replace(/r/g, "р");
    // input = input.replace(/S/g, "С");
    // input = input.replace(/s/g, "с");
    // input = input.replace(/T/g, "Т");
    // input = input.replace(/t/g, "т");
    // input = input.replace(/U/g, "Ѹ");
    // input = input.replace(/u/g, "ѹ");
    // input = input.replace(/F/g, "Ф");
    // input = input.replace(/f/g, "ф");
    // input = input.replace(/Θ/g, "Ѳ");
    // input = input.replace(/θ/g, "ѳ");
    // input = input.replace(/X/g, "Х");
    // input = input.replace(/x/g, "х");
    // input = input.replace(/Ō/g, "Ѡ");
    // input = input.replace(/ō/g, "ѡ");
    // input = input.replace(/Št/g, "Щ");
    // input = input.replace(/št/g, "щ");
    // input = input.replace(/C/g, "Ц");
    // input = input.replace(/c/g, "ц");
    // input = input.replace(/Č/g, "Ч");
    // input = input.replace(/č/g, "ч");
    // input = input.replace(/Š/g, "Ш");
    // input = input.replace(/š/g, "ш");
    // input = input.replace(/Ŭ/g, "Ъ");
    // input = input.replace(/ŭ/g, "ъ");
    // input = input.replace(/Y/g, "Ꙑ");
    // input = input.replace(/y/g, "ꙑ");
    // input = input.replace(/Ĭ/g, "Ь");
    // input = input.replace(/ĭ/g, "ь");
    // input = input.replace(/Ě/g, "Ѣ");
    // input = input.replace(/ě/g, "ѣ");
    // input = input.replace(/J/gu, "Ю");
    // input = input.replace(/j/gu, "ю");
    // input = input.replace(/Ja/g, "Ꙗ");
    // input = input.replace(/ja/g, "ꙗ");
    // input = input.replace(/Ę/g, "Ѧ");
    // input = input.replace(/ę/g, "ѧ");
    // input = input.replace(/Ǫ/g, "Ѫ");
    // input = input.replace(/ǫ/g, "ѫ");
    // input = input.replace(/Ję/g, "Ѩ");
    // input = input.replace(/ję/g, "ѩ");
    // input = input.replace(/Jǫ/g, "Ѭ");
    // input = input.replace(/jǫ/g, "ѭ");
    // input = input.replace(/K/gs, "Ѯ");
    // input = input.replace(/k/gs, "ѯ");
    // input = input.replace(/P/gs, "Ѱ");
    // input = input.replace(/p/gs, "ѱ");
    // input = input.replace(/Ü/g, "Ѵ");
    // input = input.replace(/ü/g, "ѵ");
    
    return input;
};

const glagolitic = (input) => {
    input = input.replace(/yõ/g, "Ⱙ")
    input = input.replace(/yo~/g, "Ⱙ")
    input = input.replace(/ya/g, "Ⱑ")
    input = input.replace(/yo/g, "Ⱖ")
    input = input.replace(/yu/g, "Ⱓ")
    input = input.replace(/yẽ/g, "Ⱗ")
    input = input.replace(/ye~/g, "Ⱗ")
    input = input.replace(/ẽ/g, "Ⱔ")
    input = input.replace(/e~/g, "Ⱔ")
    input = input.replace(/õ/g, "Ⱘ")
    input = input.replace(/o~/g, "Ⱘ")
    input = input.replace(/a/g, "Ⰰ")
    input = input.replace(/b/g, "Ⰱ")
    input = input.replace(/v/g, "Ⰲ")
    input = input.replace(/g/g, "Ⰳ")
    input = input.replace(/d/g, "Ⰴ")
    input = input.replace(/e/g, "Ⰵ")
    input = input.replace(/zh/g, "Ⰶ")
    input = input.replace(/dz/g, "Ⰷ")
    input = input.replace(/z/g, "Ⰸ")
    input = input.replace(/ii/g, "Ⰹ")
    input = input.replace(/iy/g, "Ⰺ")
    input = input.replace(/i/g, "Ⰻ")
    input = input.replace(/j/g, "Ⰼ")
    input = input.replace(/k/g, "Ⰽ")
    input = input.replace(/l/g, "Ⰾ")
    input = input.replace(/m/g, "Ⰿ")
    input = input.replace(/n/g, "Ⱀ")
    input = input.replace(/p/g, "ⱂ")
    input = input.replace(/r/g, "Ⱃ")
    input = input.replace(/s/g, "Ⱄ")
    input = input.replace(/t/g, "Ⱅ")
    input = input.replace(/u/g, "Ⱆ")
    input = input.replace(/f/g, "Ⱇ")
    input = input.replace(/x/g, "Ⱈ")
    input = input.replace(/oo/g, "Ⱉ")
    input = input.replace(/o/g, "Ⱁ")
    input = input.replace(/w/g, "Ⱉ")
    input = input.replace(/sht/g, "Ⱋ")
    input = input.replace(/ts/g, "Ⱌ")
    input = input.replace(/ch/g, "Ⱍ")
    input = input.replace(/sh/g, "Ⱎ")
    input = input.replace(/''/g, "Ⱏ")
    input = input.replace(/'i/g, "Ⰺ")
    input = input.replace(/'/g, "Ⱐ")
    input = input.replace(/th/g, "Ⱚ")
    input = input.replace(/v/g, "Ⱛ")
    return input;
}


export { oldslavic, glagolitic }
