const oldpersian = (input) => {
    input = input.replace(/-/g,"")
    input = input.replace(/ahuramazda1/g, "𐏈")
    input = input.replace(/ahuramazda2/g, "𐏉")
    input = input.replace(/ahuramazda3/g, "𐏊")
    input = input.replace(/xshayathia/g, "𐏋")
    input = input.replace(/dahyaus1/g, "𐏌")
    input = input.replace(/dahyaus2/g, "𐏌")
    input = input.replace(/baga/g, "𐏎")
    input = input.replace(/bumis/g, "𐏏")
    input = input.replace(/mi/g, "𐎷")
    input = input.replace(/mu/g, "𐎸")
    input = input.replace(/ku/g, "𐎤")
    input = input.replace(/xi/g, "𐎧")
    input = input.replace(/gu/g, "𐎦")
    input = input.replace(/xu/g, "𐎧")
    input = input.replace(/ji/g, "𐎪")
    input = input.replace(/ti/g, "𐎫")
    input = input.replace(/tu/g, "𐎬")
    input = input.replace(/th/g, "𐎰")
    input = input.replace(/di/g, "𐎮")
    input = input.replace(/du/g, "𐎯")
    input = input.replace(/ni/g, "𐎴")
    input = input.replace(/nu/g, "𐎵")
    input = input.replace(/vi/g, "𐎻")
    input = input.replace(/ri/g, "𐎽")
    input = input.replace(/sh/g, "𐏁")
    input = input.replace(/a/g, "𐎠")
    input = input.replace(/i/g, "𐎡")
    input = input.replace(/u/g, "𐎢")
    input = input.replace(/k/g, "𐎣")
    input = input.replace(/x/g, "𐎧")
    input = input.replace(/g/g, "𐎥")
    input = input.replace(/c/g, "𐎨")
    input = input.replace(/ç/g, "𐏂")
    input = input.replace(/j/g, "𐎩")
    input = input.replace(/t/g, "𐎫")
    input = input.replace(/d/g, "𐎭")
    input = input.replace(/p/g, "𐎱")
    input = input.replace(/f/g, "𐎳")
    input = input.replace(/b/g, "𐎲")
    input = input.replace(/n/g, "𐎴")
    input = input.replace(/m/g, "𐎶")
    input = input.replace(/y/g, "𐎹")
    input = input.replace(/v/g, "𐎺")
    input = input.replace(/r/g, "𐎼")
    input = input.replace(/l/g, "𐎾")
    input = input.replace(/s/g, "𐎿")
    input = input.replace(/z/g, "𐏀")
    input = input.replace(/š/g, "𐏁")
    input = input.replace(/h/g, "𐏃")

    return input;
}

export default oldpersian;
