const pie = (input) => {
    input = input.replace(/A\//g, "ā́")
    input = input.replace(/A/g, "ā")
    input = input.replace(/I\//g, "ī́")
    input = input.replace(/I/g, "ī")
    input = input.replace(/U\//g, "ū́")
    input = input.replace(/U/g, "ū")
    input = input.replace(/lRR\//g, "l̥̄́")
    input = input.replace(/lRR/g, "l̥̄")
    input = input.replace(/lR\//g, "ĺ̥")
    input = input.replace(/lR/g, "l̥")
    input = input.replace(/RR\//g, "r̥̄́")
    input = input.replace(/RR/g, "r̥̄")
    input = input.replace(/R\//g, "ŕ̥")
    input = input.replace(/R/g, "r̥")
    input = input.replace(/cw/g, "k̑ʷ")
    input = input.replace(/c/g, "k̑")
    input = input.replace(/kw/g, "kʷ")
    input = input.replace(/jw/g, "ĝʷ")
    input = input.replace(/j/g, "ĝ")
    input = input.replace(/bh/g, "bʰ")
    input = input.replace(/dh/g, "dʰ")
    input = input.replace(/jh/g, "ĝʰ")
    input = input.replace(/gwh/g, "gʷʰ")
    input = input.replace(/gh/g, "gʰ")
    input = input.replace(/gw/g, "gʷ")
    input = input.replace(/h1/g, "h₁")
    input = input.replace(/h2/g, "h₂")
    input = input.replace(/h3/g, "h₃")
    input = input.replace(/y/g, "i̯")
    input = input.replace(/w/g, "u̯")
    input = input.replace(/E\//g, "ḗ")
    input = input.replace(/O\//g, "ṓ")
    input = input.replace(/O/g, "ō")
    input = input.replace(/É/g, "ḗ")
    input = input.replace(/E/g, "ē")
    input = input.replace(/Ó/g, "ṓ")
    input = input.replace(/M/g, "m̥")
    input = input.replace(/N/g, "n̥")
    return input;
}

export default pie;
