const polygreek = (input) => {
    input = input.replace(/s /g,    "ς ");
    input = input.replace(/s/g,     "σ");
    input = input.replace(/b/g,     "β");
    input = input.replace(/g/g,     "γ");
    input = input.replace(/d/g,     "δ");
    input = input.replace(/z/g,     "ζ");
    input = input.replace(/q/g,     "θ");
    input = input.replace(/k/g,     "κ");
    input = input.replace(/l/g,     "λ");
    input = input.replace(/m/g,     "μ");
    input = input.replace(/n/g,     "ν");
    input = input.replace(/j/g,     "ξ");
    input = input.replace(/p/g,     "π");
    input = input.replace(/t/g,     "τ");
    input = input.replace(/c/g,     "ψ");
    input = input.replace(/x/g,     "χ");
    input = input.replace(/f/g,     "φ");
    input = input.replace(/S/g,     "Σ");
    input = input.replace(/B/g,     "Β");
    input = input.replace(/G/g,     "Γ");
    input = input.replace(/D/g,     "Δ");
    input = input.replace(/Z/g,     "Ζ");
    input = input.replace(/Q/g,     "Θ");
    input = input.replace(/K/g,     "Κ");
    input = input.replace(/L/g,     "Λ");
    input = input.replace(/M/g,     "Μ");
    input = input.replace(/N/g,     "Ν");
    input = input.replace(/J/g,     "Ξ");
    input = input.replace(/P/g,     "Π");
    input = input.replace(/R/g,     "Ρ");
    input = input.replace(/T/g,     "Τ");
    input = input.replace(/C/g,     "Ψ");
    input = input.replace(/X/g,     "Χ");
    input = input.replace(/F/g,     "Φ");


    input = input.replace(/\\\)/g,  ")\\");
    input = input.replace(/\/\)/g,  ")/");
    input = input.replace(/=\)/g,   ")=");
    input = input.replace(/\\\(/g,  "(\\");
    input = input.replace(/\/\(/g,  "(/");
    input = input.replace(/=\(/g,   "(=");

    input = input.replace(/r\(/g,   "ῥ");

    input = input.replace(/a\)\/\|/g,    "ᾄ")
    input = input.replace(/a\(\/\|/g,    "ᾅ")
    input = input.replace(/a\)\\\|/g,    "ᾂ")
    input = input.replace(/a\(\\\|/g,    "ᾃ")
    input = input.replace(/a\)=\|/g,     "ᾆ")
    input = input.replace(/a\(=\|/g,     "ᾇ")
    input = input.replace(/a\/\|/g,      "ᾴ")
    input = input.replace(/a\\\|/g,      "ᾲ")
    input = input.replace(/a=\|/g,       "ᾷ")
    input = input.replace(/a\)\|/g,      "ᾀ")
    input = input.replace(/a\(\|/g,      "ᾁ")
    input = input.replace(/a\|/g,        "ᾳ")
    input = input.replace(/a\)\//g,     "ἄ")
    input = input.replace(/a\(\//g,     "ἅ")
    input = input.replace(/a\)\\/g,     "ἂ")
    input = input.replace(/a\(\\/g,     "ἃ")
    input = input.replace(/a\)=/g,      "ἆ")
    input = input.replace(/a\(=/g,      "ἇ")
    input = input.replace(/a\//g,       "ά") 
    input = input.replace(/a\\/g,       "ὰ") 
    input = input.replace(/a=/g,        "ᾶ") 
    input = input.replace(/a\)/g,       "ἀ")
    input = input.replace(/a\(/g,       "ἁ")
    input = input.replace(/a,brevis/g,  "ᾰ")
    input = input.replace(/a,longa/g,   "ᾱ")
    input = input.replace(/a/g,         "α")
    input = input.replace(/A\)\/\|/g,    "ᾌ")
    input = input.replace(/A\(\/\|/g,    "ᾍ")
    input = input.replace(/A\)\\\|/g,    "ᾊ")
    input = input.replace(/A\(\\\|/g,    "ᾋ")
    input = input.replace(/A\)=\|/g,     "ᾎ")
    input = input.replace(/A\(=\|/g,     "ᾏ")
    input = input.replace(/A\)\|/g,      "ᾈ")
    input = input.replace(/A\(\|/g,      "ᾉ")
    input = input.replace(/A\|/g,        "ᾼ")
    input = input.replace(/A\)\//g,      "Ἄ")
    input = input.replace(/A\(\//g,      "Ἅ")
    input = input.replace(/A\)\\/g,      "Ἂ")
    input = input.replace(/A\(\\/g,      "Ἃ")
    input = input.replace(/A\)=/g,       "Ἆ")
    input = input.replace(/A\(=/g,       "Ἇ")
    input = input.replace(/A\//g,        "Ά") 
    input = input.replace(/A\\/g,        "Ὰ") 
    input = input.replace(/A\)/g,        "Ἀ")
    input = input.replace(/A\(/g,        "Ἁ")
    input = input.replace(/A,brevis/g,   "Ᾰ")
    input = input.replace(/A,longa/g,    "Ᾱ")
    input = input.replace(/A/g,          "Α")

    input = input.replace(/e\)\//g,     "ἔ")
    input = input.replace(/e\(\//g,     "ἕ")
    input = input.replace(/e\)\\/g,     "ἒ")
    input = input.replace(/e\(\\/g,     "ἓ")
    input = input.replace(/e\//g,       "έ") 
    input = input.replace(/e\\/g,       "ὲ") 
    input = input.replace(/e\)/g,       "ἐ")
    input = input.replace(/e\(/g,       "ἑ")
    input = input.replace(/e/g,         "ε")
    input = input.replace(/E\)\//g,     "Ἔ")
    input = input.replace(/E\(\//g,     "Ἕ")
    input = input.replace(/E\)\\/g,     "Ἒ")
    input = input.replace(/E\(\\/g,     "Ἓ")
    input = input.replace(/E\//g,       "Έ") 
    input = input.replace(/E\\/g,       "Ὲ") 
    input = input.replace(/E\)/g,       "Ἐ")
    input = input.replace(/E\(/g,       "Ἑ")
    input = input.replace(/E/g,         "Ε")

    input = input.replace(/h\(\/\|/g,    "ᾕ")
    input = input.replace(/h\)\/\|/g,    "ᾔ")
    input = input.replace(/h\(\\\|/g,    "ᾓ")
    input = input.replace(/h\)\\\|/g,    "ᾒ")
    input = input.replace(/h\)=\|/g,     "ᾖ")
    input = input.replace(/h\(=\|/g,     "ᾗ")
    input = input.replace(/h\/\|/g,      "ῄ")
    input = input.replace(/h\\\|/g,      "ῂ")
    input = input.replace(/h=\|/g,       "ῇ")
    input = input.replace(/h\)\|/g,      "ᾐ")
    input = input.replace(/h\(\|/g,      "ᾑ")
    input = input.replace(/h\|/g,        "ῃ")
    input = input.replace(/h\)\//g,     "ἤ")
    input = input.replace(/h\(\//g,     "ἥ")
    input = input.replace(/h\)\\/g,     "ἢ")
    input = input.replace(/h\(\\/g,     "ἣ")
    input = input.replace(/h\)=/g,      "ἦ")
    input = input.replace(/h\(=/g,      "ἧ")
    input = input.replace(/h\//g,       "ή") 
    input = input.replace(/h\\/g,       "ὴ") 
    input = input.replace(/h=/g,        "ῆ") 
    input = input.replace(/h\)/g,       "ἠ")
    input = input.replace(/h\(/g,       "ἡ")
    input = input.replace(/h/g,         "η")
    input = input.replace(/H\(\/\|/g,    "ᾝ")
    input = input.replace(/H\)\/\|/g,    "ᾜ")
    input = input.replace(/H\(\\\|/g,    "ᾛ")
    input = input.replace(/H\)\\\|/g,    "ᾚ")
    input = input.replace(/H\)=\|/g,     "ᾞ")
    input = input.replace(/H\(=\|/g,     "ᾟ")
    input = input.replace(/H\)\|/g,      "ᾘ")
    input = input.replace(/H\(\|/g,      "ᾙ")
    input = input.replace(/H\|/g,        "ῌ")
    input = input.replace(/H\)\//g,     "Ἤ")
    input = input.replace(/H\(\//g,     "Ἥ")
    input = input.replace(/H\)\\/g,     "Ἢ")
    input = input.replace(/H\(\\/g,     "Ἣ")
    input = input.replace(/H\)=/g,      "Ἦ")
    input = input.replace(/H\(=/g,      "Ἧ")
    input = input.replace(/H\//g,       "Ή") 
    input = input.replace(/H\\/g,       "Ὴ") 
    input = input.replace(/H\)/g,       "Ἠ")
    input = input.replace(/H\(/g,       "Ἡ")
    input = input.replace(/H/g,         "Η")

    input = input.replace(/i\)\//g,     "ἴ")
    input = input.replace(/i\(\//g,     "ἵ")
    input = input.replace(/i\)\\/g,     "ἲ")
    input = input.replace(/i\(\\/g,     "ἳ")
    input = input.replace(/i\)=/g,      "ἶ")
    input = input.replace(/i\(=/g,      "ἷ")
    input = input.replace(/i\//g,       "ί") 
    input = input.replace(/i\\/g,       "ὶ") 
    input = input.replace(/i=/g,        "ῖ") 
    input = input.replace(/i\)/g,       "ἰ")
    input = input.replace(/i\(/g,       "ἱ")
    input = input.replace(/i,brevis/g,  "ῐ")
    input = input.replace(/i,longa/g,   "ῑ")
    input = input.replace(/i/g,         "ι")
    input = input.replace(/I\)\//g,     "Ἴ")
    input = input.replace(/I\(\//g,     "Ἵ")
    input = input.replace(/I\)\\/g,     "Ἲ")
    input = input.replace(/I\(\\/g,     "Ἳ")
    input = input.replace(/I\)=/g,      "Ἶ")
    input = input.replace(/I\(=/g,      "Ἷ")
    input = input.replace(/I\//g,       "Ί") 
    input = input.replace(/I\\/g,       "Ὶ") 
    input = input.replace(/I\)/g,       "Ἰ")
    input = input.replace(/I\(/g,       "Ἱ")
    input = input.replace(/I,brevis/g,  "Ῐ")
    input = input.replace(/I,longa/g,   "Ῑ")
    input = input.replace(/I/g,         "Ι")

    input = input.replace(/o\)\//g,     "ὄ")
    input = input.replace(/o\(\//g,     "ὅ")
    input = input.replace(/o\)\\/g,     "ὂ")
    input = input.replace(/o\(\\/g,     "ὃ")
    input = input.replace(/o\//g,       "ό") 
    input = input.replace(/o\\/g,       "ὸ") 
    input = input.replace(/o\)/g,       "ὀ")
    input = input.replace(/o\(/g,       "ὁ")
    input = input.replace(/o/g,         "ο")
    input = input.replace(/O\)\//g,     "Ὄ")
    input = input.replace(/O\(\//g,     "Ὅ")
    input = input.replace(/O\)\\/g,     "Ὂ")
    input = input.replace(/O\(\\/g,     "Ὃ")
    input = input.replace(/O\//g,       "Ό") 
    input = input.replace(/O\\/g,       "Ὸ") 
    input = input.replace(/O\)/g,       "Ὀ")
    input = input.replace(/O\(/g,       "Ὁ")
    input = input.replace(/O/g,         "Ο")

    input = input.replace(/u\)\//g,     "ὒ")
    input = input.replace(/u\(\//g,     "ὕ")
    input = input.replace(/u\)\\/g,     "ὒ")
    input = input.replace(/u\(\\/g,     "ὓ")
    input = input.replace(/u\)=/g,      "ὖ")
    input = input.replace(/u\(=/g,      "ὗ")
    input = input.replace(/u\//g,       "ύ") 
    input = input.replace(/u\\/g,       "ὺ") 
    input = input.replace(/u=/g,        "ῦ") 
    input = input.replace(/u\)/g,       "ὐ")
    input = input.replace(/u\(/g,       "ὑ")
    input = input.replace(/u,brevis/g,  "ῠ")
    input = input.replace(/u,longa/g,   "ῡ")
    input = input.replace(/u/g,         "υ")
    input = input.replace(/U\)\//g,     "ὒ")
    input = input.replace(/U\(\//g,     "Ὕ")
    input = input.replace(/U\(\\/g,     "Ὓ")
    input = input.replace(/U\(=/g,      "Ὗ")
    input = input.replace(/U\//g,       "Ύ") 
    input = input.replace(/U\\/g,       "Ὺ") 
    input = input.replace(/V\(/g,       "Ὑ")
    input = input.replace(/U,brevis/g,  "Ῠ")
    input = input.replace(/U,longa/g,   "Ῡ")
    input = input.replace(/U/g,         "Υ")

    input = input.replace(/w\(\/\|/g,    "ᾥ")
    input = input.replace(/w\)\/\|/g,    "ᾤ")
    input = input.replace(/w\(\\\|/g,    "ᾣ")
    input = input.replace(/w\)\\\|/g,    "ᾢ")
    input = input.replace(/w\)=\|/g,     "ᾦ")
    input = input.replace(/w\(=\|/g,     "ᾧ")
    input = input.replace(/w\/\|/g,      "ῴ")
    input = input.replace(/w\\\|/g,      "ῲ")
    input = input.replace(/w=\|/g,       "ῷ")
    input = input.replace(/w\)\|/g,      "ᾠ")
    input = input.replace(/w\(\|/g,      "ᾡ")
    input = input.replace(/w\|/g,        "ῳ")
    input = input.replace(/w\)\//g,     "ὤ")
    input = input.replace(/w\(\//g,     "ὥ")
    input = input.replace(/w\)\\/g,     "ὢ")
    input = input.replace(/w\(\\/g,     "ὣ")
    input = input.replace(/w\)=/g,      "ὦ")
    input = input.replace(/w\(=/g,      "ὧ")
    input = input.replace(/w\//g,       "ώ") 
    input = input.replace(/w\\/g,       "ὼ") 
    input = input.replace(/w=/g,        "ῶ") 
    input = input.replace(/w\)/g,       "ὠ")
    input = input.replace(/w\(/g,       "ὡ")
    input = input.replace(/w/g,         "ω")
    input = input.replace(/W\(\/\|/g,    "ᾭ")
    input = input.replace(/W\)\/\|/g,    "ᾬ")
    input = input.replace(/W\(\\\|/g,    "ᾫ")
    input = input.replace(/W\)\\\|/g,    "ᾪ")
    input = input.replace(/W\)=\|/g,     "ᾮ")
    input = input.replace(/W\(=\|/g,     "ᾯ")
    input = input.replace(/W\)\|/g,      "ᾨ")
    input = input.replace(/W\(\|/g,      "ᾩ")
    input = input.replace(/W\|/g,        "ῼ")
    input = input.replace(/W\)\//g,     "Ὤ")
    input = input.replace(/W\(\//g,     "Ὥ")
    input = input.replace(/W\)\\/g,     "Ὢ")
    input = input.replace(/W\(\\/g,     "Ὣ")
    input = input.replace(/W\)=/g,      "Ὦ")
    input = input.replace(/W\(=/g,      "Ὧ")
    input = input.replace(/W\//g,       "Ώ") 
    input = input.replace(/W\\/g,       "Ὼ") 
    input = input.replace(/W\)/g,       "Ὠ")
    input = input.replace(/W\(/g,       "Ὡ")
    input = input.replace(/W/g,         "Ω")

    input = input.replace(/r/g,     "ρ");

    return input;
}

export default polygreek
